apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-access
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["pods", "services", "persistentvolumeclaims", "configmaps", "secrets", "replicationcontrollers", "events", "namespaces", "nodes", "statefulsets", "daemonsets", "replicasets", "deployments", "jobs", "cronjobs", "ingresses" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-access
subjects:
- kind: ServiceAccount
  name: dashboard-access
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: dashboard-access
  apiGroup: rbac.authorization.k8s.io