apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
      - name: echo1
        image: k8s.gcr.io/echoserver:1.10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /etc/configmap
            name: conf-mount
      nodeName: l2-cluster-master
      volumes:
        - name: conf-mount
          configMap:
              name: testconf