apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  selector:
    app: jupyter
  ports:
  - port: 80
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      imagePullSecrets:
        - name: githubkey
      containers:
      - name: jupyter
        image: registry.l2.team/operator/jupyter:latest
        ports:
        - containerPort: 8888
        volumeMounts:
          - mountPath: /notebooks
            name: notebooks
      volumes:
        - name: notebooks
          persistentVolumeClaim:
              claimName: jupyter
