apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: telemetry
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-zipkin
  namespace: telemetry
spec:
  selector:
    matchLabels:
      app: mysql-zipkin
  template:
    metadata:
      labels:
        app: mysql-zipkin
    spec:
      containers:
      - name: mysql-zipkin
        image: openzipkin/zipkin-mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: "mysql-data"
      volumes:
      - name: "mysql-data"
        persistentVolumeClaim:
          claimName: "mysql-data"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-zipkin
  namespace: telemetry
spec:
  selector:
    app: mysql-zipkin
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: telemetry
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
        - containerPort: 9411
        env:
          - name: STORAGE_TYPE
            value: mysql
          - name: MYSQL_USER
            value: zipkin
          - name: MYSQL_PASS
            value: zipkin
          - name: MYSQL_HOST
            value: mysql-zipkin.telemetry.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: telemetry
spec:
  selector:
    app: zipkin
  ports:
  - port: 9411
    targetPort: 9411